# Generated by Django 4.0.5 on 2022-06-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_team_slug'),
        ('Ingame', '0002_cocwar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocwar',
            name='home_tag',
        ),
        migrations.RemoveField(
            model_name='cocwar',
            name='opponent_tag',
        ),
        migrations.AddField(
            model_name='cocwar',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Team.team'),
        ),
        migrations.AddField(
            model_name='cocwar',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_team', to='Team.team'),
        ),
    ]
