# Generated by Django 4.0.5 on 2022-06-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='std_roster',
            field=models.ManyToManyField(blank=True, to='Tournament.possibleroster'),
        ),
    ]
