# Generated by Django 4.0.5 on 2022-06-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0002_tournament_std_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tracking_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
