# Generated by Django 4.0.5 on 2022-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0003_tournament_tracking_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='on_registration',
            field=models.BooleanField(default=True),
        ),
    ]
