# Generated by Django 4.0.5 on 2022-06-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0004_tournament_on_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='associated_color',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
