# Generated by Django 4.0.5 on 2022-06-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_team_slug'),
        ('Tournament', '0005_tournament_associated_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_round', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('negociated_date', models.DateField(blank=True, null=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('score', models.CharField(blank=True, max_length=122, null=True)),
                ('home_result', models.CharField(blank=True, choices=[('win', 'Win'), ('lose', 'Lose'), ('tie', 'Tie')], max_length=5, null=True)),
                ('opponent_result', models.CharField(blank=True, choices=[('win', 'Win'), ('lose', 'Lose'), ('tie', 'Tie')], max_length=5, null=True)),
                ('is_exempt', models.BooleanField(default=False)),
                ('home_forfeit', models.BooleanField(default=False)),
                ('opponent_forfeit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tournament.tournament')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Team.team')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opp', to='Team.team')),
                ('roster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tournament.possibleroster')),
            ],
        ),
    ]
