# Generated by Django 4.0.5 on 2022-06-22 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0006_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tournament.tournament'),
        ),
    ]
