# Generated by Django 4.0.5 on 2022-07-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentPossibleConf', '0001_initial'),
        ('Tournament', '0007_remove_match_competition_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TournamentPossibleConf.possibleroster'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='placement_conf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TournamentPossibleConf.possibleplacementconf'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='std_match_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TournamentPossibleConf.possiblematchformat'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='std_roster',
            field=models.ManyToManyField(blank=True, to='TournamentPossibleConf.possibleroster'),
        ),
        migrations.DeleteModel(
            name='PossibleMatchFormat',
        ),
        migrations.DeleteModel(
            name='PossiblePlacementConf',
        ),
        migrations.DeleteModel(
            name='PossibleRoster',
        ),
    ]
