# Generated by Django 4.0.5 on 2022-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Referent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=4)),
                ('discord_server_id', models.IntegerField(default=0)),
                ('discord_server_invit', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('discord_staff_members', models.ManyToManyField(to='Referent.referent')),
            ],
        ),
    ]
