# Generated by Django 4.0.5 on 2022-06-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_alter_organization_discord_staff_members_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleMatchFormat',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('code_name', models.CharField(blank=True, max_length=164, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('team_size', models.IntegerField(blank=True, choices=[(None, None), (5, '5vs5'), (10, '10vs10'), (15, '15vs15'), (20, '20vs20'), (25, '25vs25'), (30, '30vs30'), (35, '35vs35'), (40, '40vs40'), (45, '45vs45'), (50, '50vs50')], null=True)),
                ('prep_duration', models.DurationField(blank=True, null=True)),
                ('war_duration', models.DurationField(blank=True, null=True)),
                ('attack_per_member', models.IntegerField(blank=True, choices=[(None, None), (1, '1 attaque'), (2, '2 attaques')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='std_match_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organization.possiblematchformat'),
        ),
    ]
