# Generated by Django 4.0.5 on 2022-06-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tournament', '0002_tournament_std_roster'),
        ('Ingame', '0001_initial'),
        ('Referent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('roster', models.CharField(choices=[(None, None), ('Mixt', 'Mixt'), ('Full', 'Full')], default=None, max_length=6)),
                ('registered_for_round', models.IntegerField(blank=True, default=0, null=True)),
                ('is_staff_validated', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('blason_url', models.URLField(blank=True, null=True)),
                ('played_matchs', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active_clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ingame.cocclan')),
                ('referent_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Referent.referent')),
                ('second_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_referent', to='Referent.referent')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tournament.tournament')),
            ],
        ),
    ]
