# Generated by Django 4.0.5 on 2022-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleMatchFormat',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('code_name', models.CharField(blank=True, max_length=164, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('team_size', models.IntegerField(blank=True, choices=[(None, None), (5, '5vs5'), (10, '10vs10'), (15, '15vs15'), (20, '20vs20'), (25, '25vs25'), (30, '30vs30'), (35, '35vs35'), (40, '40vs40'), (45, '45vs45'), (50, '50vs50')], null=True)),
                ('prep_duration', models.DurationField(blank=True, null=True)),
                ('war_duration', models.DurationField(blank=True, null=True)),
                ('attack_per_member', models.IntegerField(blank=True, choices=[(None, None), (1, '1 attaque'), (2, '2 attaques')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PossiblePlacementConf',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=132)),
                ('direct_elimination', models.BooleanField(default=False)),
                ('by_group', models.BooleanField(default=False)),
                ('play_off', models.BooleanField(default=False)),
                ('pts_for_win', models.IntegerField(default=0)),
                ('pts_for_tie', models.IntegerField(default=0)),
                ('pts_for_played', models.IntegerField(default=0)),
                ('first_critere', models.CharField(blank=True, max_length=22, null=True)),
                ('second_critere', models.CharField(blank=True, max_length=22, null=True)),
                ('three_critere', models.CharField(blank=True, max_length=22, null=True)),
                ('four_citere', models.CharField(blank=True, max_length=22, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleRoster',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=132)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
