# Generated by Django 4.0.5 on 2022-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referent',
            fields=[
                ('discord_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('discriminator', models.IntegerField(blank=True)),
                ('member_avatar', models.URLField(blank=True, null=True)),
                ('guild', models.CharField(blank=True, max_length=32, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
