# Generated by Django 4.0.5 on 2022-06-22 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0007_remove_match_competition_match_tournament'),
        ('Tos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currenttos',
            name='competition',
        ),
        migrations.AddField(
            model_name='currenttos',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tournament.tournament'),
        ),
    ]
